### ISSUE TITLE
Исправление Route

### ISSUE THREAD

**Issue by GhostWalkers** [illogical-ru/lava#1]
Здравствуйте, притензий к библиотеке нет кроме route системы, она оказалось в пункте 404, советую убрать проверку в отдельный метод и назвать его bootRoute

**Comment by GhostWalkers** [comment]
![image](https://user-images.githubusercontent.com/100309290/161813950-dfeccccb-fc35-4f6c-94a4-566a3a6c79a7.png)
мое предложение такое

**Comment by GhostWalkers** [comment]
хотя-бы понятно откуда ноги у роутов растут :)

**Comment by illogical-ru** [comment]
Здравствуйте, обработка 404 не должна лежать на библиотеке, это задача приложения
В данный момент в репозитории есть только библиотека, пример приложения убрал, для него будет отдельный репозиторий

**Comment by GhostWalkers** [comment]
у вас отличная база фреймворка (гибкая) :)

**Comment by GhostWalkers** [comment]
Я согласен что 404 это проблема самого приложение, но сделайте эту самую загрузку более явной)

**Comment by illogical-ru** [comment]
Не очень понимаю, можно пример как сделать более явно?
Есть метод routes_match, который запускает поиск подходящих маршрутов и возвращает количество выполненных обработчиков и если приложению нужно выполнить какие то действия или отобразить страницу 404, то оно это делает само, если routes_match возвращает 0

**Comment by GhostWalkers** [comment]
Просто сам запуск роут системы получается в ошибке 404 :) я предлагаю сделать поиск маршрута в переменную, по типу $route = findRoute();
if (!route)... Так будет более понятно что и куда, а то получается у вас, если есть то require, если нет то брек

**Comment by GhostWalkers** [comment]
Тобишь отделить момент 404 и роут в принципе

**Comment by illogical-ru** [comment]
Они и не связаны, просто результат routes_match можно использовать, при необходимости, для отображения ошибки 404, если маршрут не найден
И чем отличается пример выше от $match = App::routes_match()
if (!$match) ...
Или можно унаследовать основной класс, добавить метод со скриншота bootRouteSystem и вызывать его

**Comment by GhostWalkers** [comment]
Хорошо, спасибо
